spring.application.name=auction
spring.datasource.url=jdbc:mysql://localhost:3306/auction_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:

spring.jpa.open-in-view=false

app.bootstrap.admin-username=admin
app.bootstrap.admin-password=Admin@123
app.bootstrap.admin-email=admin@auction.local
app.auction.close-check-delay-ms=5000
app.jwt.secret=ChangeThisJwtSecretToAtLeast32CharactersLong12345
app.jwt.expiration-ms=3600000
